version: '3.7'

services:
  mqtt-broker:
    container_name: mqtt-broker
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - net1

networks:
  net1:
    driver: bridge
